#!/usr/bin/expect -f
#
# ptssign : expect powered rpm signing command
#

proc usage {} {
        send_user "Usage: ptssign passphrase rpmfile\n\n"
        exit
}

if {[llength $argv]!=2} usage

set PASSPHRASE [lrange $argv 0 0]
set RPMFILE [lrange $argv 1 1]

spawn rpm --addsign $RPMFILE
expect -exact "Enter pass phrase: "
send -- "$PASSPHRASE\r"
expect eof
